### ISSUE TITLE
Parse error: syntax error, unexpected '1' (T_LNUMBER), expecting identifier (T_STRING) in stk/includes/functions.php(955) : eval()'d code on line 1

### ISSUE THREAD

**Issue by pvekatexpert** [AlexSheer/phpBB3.2-STK#1]
Hello,
I have a bug with the code.
When I run the script, I have this error.

Error 4: syntax error, unexpected '1' (T_LNUMBER), expecting identifier (T_STRING) at file /stk/includes/functions.php(955) : eval()'d code line 1

Can you help me?

function :  function html_entity_decode_utf8($string)
line :	 $string = preg_replace_callback('|&#([0-9]+);|', function($matches) use($replacement) {eval('$str=' . $replacement); return $str;}, $string);

**Comment by AlexSheer** [comment]
Fixed https://github.com/AlexSheer/phpBB3.2-STK/commit/87278c8d56a3f7e410b93d915760ff156e94535e#diff-f81f3dff36bf04b7a070d642c858e883
