### ISSUE TITLE
reparse_bbcode.php throws error (double WHERE-clause in MySQL-statement)

### ISSUE THREAD

**Issue by PeeteeNL** [AlexSheer/phpBB3.2-STK#14]
While trying to reparse a forum (all content):

[phpBB Debug] PHP : in file [ROOT]/phpbb/db/driver/driver.php on line 999: SQL ERROR [ mysqli ]
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB
server version for the right syntax to use near 'WHERE forum_id = 101' at line 3 [1064]
SQL
SELECT COUNT(post_id) AS cnt FROM phpbb_posts **WHERE** bbcode_bitfield <> '' **WHERE**
forum_id = 101
FILE: (not given by php)
LINE: (not given by php)
CALL: stk_msg_handler()
FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 999
CALL: trigger_error()
FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()
FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()
FILE: [ROOT]/stk/tools/admin/reparse_bbcode.php
LINE: 251
CALL: phpbb\db\driver\factory->sql_query()
FILE: [ROOT]/stk/index.php
LINE: 293
CALL: reparse_bbcode->run_tool()
BACKTRACE
FILE: (not given by php)
LINE: (not given by php)
CALL: stk_msg_handler()
FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 999
CALL: trigger_error()
FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()
FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()
FILE: [ROOT]/stk/tools/admin/reparse_bbcode.php
LINE: 251
CALL: phpbb\db\driver\factory->sql_query()
FILE:

**Comment by AlexSheer** [comment]
If you choose Reparsing only in selected forums, then you do not have to choose the Reparsing of absolutely all BBCode. One out of two.
Вut fix here https://github.com/AlexSheer/phpBB3.2-STK/commit/c57f6944b0dbc22e9a0df38b30a40a6727965d9a#diff-fa3962e701680907e3cd1837c3adc1ca

**Comment by PeeteeNL** [comment]
Thanks very much. No error anymore. Only, the posts in the underlying topics in the selected forums are **not** reparsed. The only option that really works for me is to reparse individual posts. Nothing else workes. How come? Hope you can help me out here ... 

Grtz PeeteeNL

**Comment by PeeteeNL** [comment]
I read the frase "by **default**, the tool will only reparse posts/private messages/signatures that have been previously parsed by phpBB". These posts however are imported posts from IPB. How can I override the default to reparse all posts?
