### ISSUE TITLE
Cannor Reparse BBCode on 3.2.1 with some extensions installed

### ISSUE THREAD

**Issue by Leinad4Mind** [AlexSheer/phpBB3.2-STK#16]
[phpBB Debug] PHP : in file [ROOT]/phpbb/db/driver/driver.php on line 999: SQL ERROR [ mysqli ]
Column 'topic_desc' cannot be null [1048]

topic_desc has values, its not null (This was from topic description ext)

**Comment by Leinad4Mind** [comment]
I just add: t.topic_desc to the line 331 on tools/reparse_bbcode.php and its all working :)

**Comment by AlexSheer** [comment]
https://github.com/AlexSheer/phpBB3.2-STK/commit/ae71d5410962f06eb1e55742f9d789081cd43fa4#diff-fa3962e701680907e3cd1837c3adc1ca
