### ISSUE TITLE
Error when cleaning data base

### ISSUE THREAD

**Issue by flc85** [AlexSheer/phpBB3.2-STK#2]
[phpBB Debug] PHP Notice: in file [ROOT]/includes/database_cleaner/database_cleaner_views.php on line 167: 
[phpBB Debug] PHP Notice: in file [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php on line 167: Undefined index: INTRODUCTION

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 167
CALL: stk_msg_handler()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

BACKTRACE

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 167
CALL: stk_msg_handler()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

[phpBB Debug] PHP Notice: in file [ROOT]/includes/database_cleaner/database_cleaner_views.php on line 169: 
[phpBB Debug] PHP Notice: in file [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php on line 169: Undefined index: INDEXES

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 169
CALL: stk_msg_handler()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

BACKTRACE

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 169
CALL: stk_msg_handler()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

[phpBB Debug] PHP Notice: in file [ROOT]/includes/database_cleaner/database_cleaner_views.php on line 172: 
[phpBB Debug] PHP Notice: in file [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php on line 172: Undefined index: ACP_EXTENSION_GROUPS

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 172
CALL: stk_msg_handler()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

BACKTRACE

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 172
CALL: stk_msg_handler()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

[phpBB Debug] PHP Notice: in file [ROOT]/includes/database_cleaner/database_cleaner_views.php on line 173: 
[phpBB Debug] PHP Notice: in file [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php on line 173: Undefined index: EXTENSION_FILE_GROUPS

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 173
CALL: stk_msg_handler()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

BACKTRACE

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 173
CALL: stk_msg_handler()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

[phpBB Debug] PHP Notice: in file [ROOT]/includes/database_cleaner/database_cleaner_views.php on line 175: 
[phpBB Debug] PHP Notice: in file [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php on line 175: Undefined index: SYSTEM_GROUPS

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 175
CALL: stk_msg_handler()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

BACKTRACE

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 175
CALL: stk_msg_handler()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

[phpBB Debug] PHP Warning: in file /home/meteofon/public_html/forum/includes/functions.php on line 4511: 
[phpBB Debug] PHP Runtime Error: in file [ROOT]/includes/functions.php on line 4511: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:692)

FILE: (not given by php)
LINE: (not given by php)
CALL: stk_msg_handler()

FILE: [ROOT]/includes/functions.php
LINE: 4511
CALL: header()

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 207
CALL: page_header()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: stk_msg_handler()

FILE: [ROOT]/includes/functions.php
LINE: 4511
CALL: header()

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 207
CALL: page_header()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

[phpBB Debug] PHP Warning: in file /home/meteofon/public_html/forum/includes/functions.php on line 4511: 
[phpBB Debug] PHP Runtime Error: in file [ROOT]/includes/functions.php on line 4511: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:692)

FILE: (not given by php)
LINE: (not given by php)
CALL: stk_msg_handler()

FILE: [ROOT]/includes/functions.php
LINE: 4511
CALL: header()

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 207
CALL: page_header()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: stk_msg_handler()

FILE: [ROOT]/includes/functions.php
LINE: 4511
CALL: header()

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 207
CALL: page_header()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

[phpBB Debug] PHP Warning: in file /home/meteofon/public_html/forum/includes/functions.php on line 4511: 
[phpBB Debug] PHP Runtime Error: in file [ROOT]/includes/functions.php on line 4511: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:692)

FILE: (not given by php)
LINE: (not given by php)
CALL: stk_msg_handler()

FILE: [ROOT]/includes/functions.php
LINE: 4511
CALL: header()

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 207
CALL: page_header()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: stk_msg_handler()

FILE: [ROOT]/includes/functions.php
LINE: 4511
CALL: header()

FILE: [ROOT]/stk/includes/database_cleaner/database_cleaner_views.php
LINE: 207
CALL: page_header()

FILE: [ROOT]/stk/tools/support/database_cleaner.php
LINE: 177
CALL: database_cleaner_views->display()

FILE: [ROOT]/stk/index.php
LINE: 302
CALL: database_cleaner->display_options()

**Comment by AlexSheer** [comment]
What language are you using?

**Comment by flc85** [comment]
French language

**Comment by AlexSheer** [comment]
In your language files are missing variables. Try to use English instead of French
