### ISSUE TITLE
Two minor issues

### ISSUE THREAD

**Issue by kasimi** [AlexSheer/phpBB3.2-STK#24]
In `includes/database_cleaner/database_cleaner_controller.php`:

* line 847: `$reason_id` is undefined
* line 1054: `$acp_tools = new acp_modules();` should be moved outsite of the if-block

**Comment by Galixte** [comment]
Hi @AlexSheer,

could you take a look, please?

**Comment by AlexSheer** [comment]
>     * line 1054: `$acp_tools = new acp_modules();` should be moved outsite of the if-bloc

For what reason?

>     * line 847: `$reason_id` is undefined

Probably need so `WHERE reason_id = ' . (int) $row['reason_id'];`
