### ISSUE TITLE
error with purge cache

### ISSUE THREAD

**Issue by flc85** [AlexSheer/phpBB3.2-STK#3]
[phpBB Debug] PHP Notice: in file [ROOT]/index.php on line 389: 
[phpBB Debug] PHP Notice: in file [ROOT]/stk/index.php on line 389: Undefined index: PURGE_CACHE_CONFIRM

FILE: [ROOT]/stk/index.php
LINE: 389
CALL: stk_msg_handler()

BACKTRACE

FILE: [ROOT]/stk/index.php
LINE: 389
CALL: stk_msg_handler()

**Comment by AlexSheer** [comment]
In your language files are missing variables. Try to use English instead of French
