### ISSUE TITLE
Primary script unknown

### ISSUE THREAD

**Issue by Solidjeuh** [AlexSheer/phpBB3.2-STK#38]
I have an error in server logs when visiting STK

`[Sat Aug 24 23:33:29.660360 2019] [proxy_fcgi:error] [pid 8360:tid 139690692380416] [client 62.141.44.187:43842] AH01071: Got error 'Primary script unknown\n', referer: https://www.supportforum.be/stk/
`
Forum version: 3.2.8-RC1
System: Linux 3.10.0-042stab138.1
Webserver: Apache
PHP version: 7.2.21 (FPM application served by apache)
Database server: MySQL(i) 5.5.60-MariaDB
Operating system: Redhat
CPU: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz

**Comment by AlexSheer** [comment]
No any problems
![Screenshot_1](https://user-images.githubusercontent.com/9640205/64325272-7e435580-cfd0-11e9-8756-a7bb7324655d.png)
