### ISSUE TITLE
passwd.php - login method is failed

### ISSUE THREAD

**Issue by Galixte** [AlexSheer/phpBB3.2-STK#43]
Hi @AlexSheer,

if I try to login in with passwd.php method I encounter this red message: “The submitted form was invalid: Try submitting again.”

Is this phpBB issue is related to this error: https://tracker.phpbb.com/browse/PHPBB3-16066?

Regards.

**Comment by neuropass** [comment]
password login not working! invalid form!

https://gyazo.com/99c49cd284e7a44c0a8013250ac1906e

**Comment by neuropass** [comment]
under phpBB 3.3.0 invalid form error

**Comment by Galixte** [comment]
@neuropass 3.3.1 version with this patch is better? https://github.com/AlexSheer/phpBB3.2-STK/pull/51

**Comment by neuropass** [comment]
But those fixes have nothing to do with the password authentication?

**Comment by sslorigin** [comment]
> But those fixes have nothing to do with the password authentication?

What the meaning by the password authentication?

**Comment by neuropass** [comment]
@sslorigin @AlexSheer  the issue is documented below. 

> 
> 
> Hi @AlexSheer,
> 
> if I try to login in with passwd.php method I encounter this red message: “The submitted form was invalid: Try submitting again.”
> 
> Is this phpBB issue is related to this error: https://tracker.phpbb.com/browse/PHPBB3-16066?
> 
> Regards.

**Comment by AlexSheer** [comment]
Fixed https://github.com/AlexSheer/phpBB3.2-STK/commit/f252a4ebe088c4b5adf3ea5670b58dc467ee6037#diff-828e0013b8f3bc1bb22b4f57172b019d

**Comment by Galixte** [comment]
> Fixed [f252a4e#diff-828e0013b8f3bc1bb22b4f57172b019d](https://github.com/AlexSheer/phpBB3.2-STK/commit/f252a4ebe088c4b5adf3ea5670b58dc467ee6037#diff-828e0013b8f3bc1bb22b4f57172b019d)

Thanks dude!
