### ISSUE TITLE
REPARSE BBCODE

### ISSUE THREAD

**Issue by MixingOnBeat** [AlexSheer/phpBB3.2-STK#5]
When I ran REPARSE BBCODE it fixed a problem I was having after my upgrade from phpBB 3.1.x to 3.2.  See here for more details: https://www.phpbb.com/community/viewtopic.php?p=14715281#p14715281

But I noticed a bug.  It created blank POLLS on some old posts and also it locked a few of them.

I don't know why that happened, but I find this to a be strange.

Keep in mind that I've had this database since phpBB 2.0.x and I've upgraded this database each time during each phase of phpBB updates.

So I restored my backup database prior to doing the REPARSE BBCODE fix.  I'd like to try again, but I fear that it will create dummy POLLS and lock up some topics.  Not sure why at this point?

**Comment by MixingOnBeat** [comment]
I just wanted to give you an update.  It turns out, it was not STK fault about the dummy polls.  It was another issue explained in this reply: https://www.phpbb.com/community/viewtopic.php?p=14716806#p14716806

Still looking to see why some of those posts were also locked.  If I find something, I'll let you know.

**Comment by Galixte** [comment]
so you can close ;)
