### ISSUE TITLE
phpBB3.2-STK language error?  in phpBB 3.3.2

### ISSUE THREAD

**Issue by Procstas** [AlexSheer/phpBB3.2-STK#54]
This error appears on opening /phpBB3/stk
default_lang.txt is set to: en

Error 1: Uncaught Error: Attempt to modify property "data" on null in F:\phpBB3\stk\includes\functions.php:290 
Stack trace: 
#0 F:\phpBB3\stk\includes\functions.php(593): stk_add_lang() 
#1 [internal function]: stk_msg_handler() 
#2 F:\phpBB3\vendor\symfony\dependency-injection\Container.php(190): trigger_error() 
#3 F:\phpBB3\phpbb\di\container_builder.php(223): Symfony\Component\DependencyInjection\Container->set() 
#4 F:\phpBB3\common.php(115): phpbb\di\container_builder->get_container() 
#5 F:\phpBB3\stk\common.php(39): require('...') 
#6 F:\phpBB3\stk\index.php(18): require('...') 
#7 {main} thrown at file F:\phpBB3\stk\includes\functions.php line 290

**Comment by AlexSheer** [comment]
Try it
[default_lang.txt](https://github.com/AlexSheer/phpBB3.2-STK/files/5899324/default_lang.txt)

**Comment by Procstas** [comment]
As I said, default_lang.txt was already set to en
Now I replaced the file with your "Try it"  default_lang.txt.
Result is the same:
Error 1: Uncaught Error: Attempt to modify property "data" on null in F:\phpBB3\stk\includes\functions.php:290 Stack trace: #0 F:\phpBB3\stk\includes\functions.php(593): stk_add_lang() #1 [internal function]: stk_msg_handler() #2 F:\phpBB3\vendor\symfony\dependency-injection\Container.php(190): trigger_error() #3 F:\phpBB3\phpbb\di\container_builder.php(223): Symfony\Component\DependencyInjection\Container->set() #4 F:\phpBB3\common.php(115): phpbb\di\container_builder->get_container() #5 F:\phpBB3\stk\common.php(39): require('...') #6 F:\phpBB3\stk\index.php(18): require('...') #7 {main} thrown at file F:\phpBB3\stk\includes\functions.php line 290

**Comment by AlexSheer** [comment]
Fixed https://github.com/AlexSheer/phpBB3.2-STK/commit/4270711155053a78ff5bd2e92f2467b039bf85f1
