### ISSUE TITLE
Issue with php 8.0.1 version

### ISSUE THREAD

**Issue by sslorigin** [AlexSheer/phpBB3.2-STK#55]
Hi AlexSheer
I use 1.0.17-dev version with a version 7.4 of php without trouble.

With 8.0.1 version i have this message:

`Fatal error: Uncaught Error: Attempt to modify property "data" on null in /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/tools/includes/functions.php:290 Stack trace: #0 /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/tools/includes/functions.php(593): stk_add_lang('common') #1 [internal function]: stk_msg_handler(16384, 'The "config.php...', '/home/clients/a...', 190) #2 /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/vendor/symfony/dependency-injection/Container.php(190): trigger_error('The "config.php...', 16384) #3 /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/phpbb/di/container_builder.php(234): Symfony\Component\DependencyInjection\Container->set('config.php', Object(phpbb\config_php_file)) #4 /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/common.php(115): phpbb\di\container_builder->get_container() #5 /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/tools/common.php(39): require('/home/clients/a...') #6 /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/tools/index.php(18): require('/home/clients/a...') #7 {main} thrown in /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/tools/includes/functions.php on line 290
Error 1: Uncaught Error: Attempt to modify property "data" on null in /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/tools/includes/functions.php:290 Stack trace: #0 /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/tools/includes/functions.php(593): stk_add_lang('common') #1 [internal function]: stk_msg_handler(16384, 'The "config.php...', '/home/clients/a...', 190) #2 /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/vendor/symfony/dependency-injection/Container.php(190): trigger_error('The "config.php...', 16384) #3 /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/phpbb/di/container_builder.php(234): Symfony\Component\DependencyInjection\Container->set('config.php', Object(phpbb\config_php_file)) #4 /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/common.php(115): phpbb\di\container_builder->get_container() #5 /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/tools/common.php(39): require('/home/clients/a...') #6 /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/tools/index.php(18): require('/home/clients/a...') #7 {main} thrown at file /home/clients/aad2674d94bf9fbeb384ebc8b7e1c3be/web/forum/tools/includes/functions.php line 290`

Thanks a lot

**Comment by AlexSheer** [comment]
https://github.com/AlexSheer/phpBB3.2-STK/commit/4270711155053a78ff5bd2e92f2467b039bf85f1

**Comment by sslorigin** [comment]
Great, thanks a lot
