### ISSUE TITLE
reparse bbcode mysql error

### ISSUE THREAD

**Issue by nikolaleon** [AlexSheer/phpBB3.2-STK#6]
I try to do this; http://prntscr.com/fzicqt

And I get this:

[phpBB Debug] PHP Notice: in file /home/pokemon9/public_html/Forum/ext/part3/topicprefixes/event/listener.php on line 147:
[phpBB Debug] PHP Notice: in file [ROOT]/ext/part3/topicprefixes/event/listener.php on line 147: Undefined index: topic_prefix

FILE: [ROOT]/ext/part3/topicprefixes/event/listener.php
LINE: 147
CALL: stk_msg_handler()

FILE: (not given by php)
LINE: (not given by php)
CALL: part3/topicprefixes/event/listener->submit_post_modify_sql_data()

FILE: [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php
LINE: 184
CALL: call_user_func()

FILE: [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php
LINE: 46
CALL: Symfony/Component/EventDispatcher/EventDispatcher->doDispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 60
CALL: Symfony/Component/EventDispatcher/EventDispatcher->dispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 46
CALL: phpbb/event/dispatcher->dispatch()

FILE: [ROOT]/includes/functions_posting.php
LINE: 1812
CALL: phpbb/event/dispatcher->trigger_event()

FILE: [ROOT]/stk/tools/admin/reparse_bbcode.php
LINE: 428
CALL: submit_post()

FILE: [ROOT]/stk/index.php
LINE: 293
CALL: reparse_bbcode->run_tool()

BACKTRACE

FILE: [ROOT]/ext/part3/topicprefixes/event/listener.php
LINE: 147
CALL: stk_msg_handler()

FILE: (not given by php)
LINE: (not given by php)
CALL: part3\topicprefixes\event\listener->submit_post_modify_sql_data()

FILE: [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php
LINE: 184
CALL: call_user_func()

FILE: [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php
LINE: 46
CALL: Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 60
CALL: Symfony\Component\EventDispatcher\EventDispatcher->dispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 46
CALL: phpbb\event\dispatcher->dispatch()

FILE: [ROOT]/includes/functions_posting.php
LINE: 1812
CALL: phpbb\event\dispatcher->trigger_event()

FILE: [ROOT]/stk/tools/admin/reparse_bbcode.php
LINE: 428
CALL: submit_post()

FILE: [ROOT]/stk/index.php
LINE: 293
CALL: reparse_bbcode->run_tool()

Warning: Cannot modify header information - headers already sent by (output started at /home/pokemon9/public_html/Forum/stk/includes/functions.php:694) in /home/pokemon9/public_html/Forum/stk/includes/functions.php on line 1070
Return to index page
General Error

[phpBB Debug] PHP : in file [ROOT]/phpbb/db/driver/driver.php on line 999: SQL ERROR [ mysqli ]

Column 'topic_prefix' cannot be null [1048]

SQL

UPDATE phpbb_topics SET forum_id = '27', icon_id = '0', topic_title = 'Bleach!', topic_first_poster_name = 'Buddha', topic_type = '0', topic_time_limit = 0, poll_title = '', poll_start = '1427385840', poll_max_options = '1', poll_length = 0, poll_vote_change = '0', topic_last_view_time = '1427385840', topic_attachment = 0, topic_prefix = NULL WHERE topic_id = 470

FILE: (not given by php)
LINE: (not given by php)
CALL: stk_msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 999
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/includes/functions_posting.php
LINE: 1890
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/stk/tools/admin/reparse_bbcode.php
LINE: 428
CALL: submit_post()

FILE: [ROOT]/stk/index.php
LINE: 293
CALL: reparse_bbcode->run_tool()

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: stk_msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 999
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/includes/functions_posting.php
LINE: 1890
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/stk/tools/admin/reparse_bbcode.php
LINE: 428
CALL: submit_post()

FILE: [ROOT]/stk/index.php
LINE: 293
CALL: reparse_bbcode->run_tool()

**Comment by Galixte** [comment]
Hi @nikolaleon,

you have to disable this extension (like mentioned in your error messages): https://www.phpbb.com/community/viewtopic.php?f=456&t=2357986 before to use STK for phpBB 3.2.x.

Disable all your extensions (just disable no delete data) before to use this tool and make a db save also.
