### ISSUE TITLE
Error when HIDE BBCode is active

### ISSUE THREAD

**Issue by miri4ever** [AlexSheer/phpBB3.2-STK#7]
Always when I try to open STK I got this error from HIDE BBCode Extension:

[phpBB Debug] PHP Notice: in file [ROOT]/ext/marcovo/hideBBcode/event/listener.php on line 114: Indirect modification of overloaded property phpbb\user::$lang has no effect

FILE: [ROOT]/ext/marcovo/hideBBcode/event/listener.php
LINE: 114
CALL: stk_msg_handler()

FILE: (not given by php)
LINE: (not given by php)
CALL: marcovo\hideBBcode\event\listener->load_language_on_setup()

FILE: [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php
LINE: 184
CALL: call_user_func()

FILE: [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php
LINE: 46
CALL: Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 60
CALL: Symfony\Component\EventDispatcher\EventDispatcher->dispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 46
CALL: phpbb\event\dispatcher->dispatch()

FILE: [ROOT]/phpbb/user.php
LINE: 219
CALL: phpbb\event\dispatcher->trigger_event()

FILE: [ROOT]/stk/common.php
LINE: 60
CALL: phpbb\user->setup()

FILE: [ROOT]/stk/index.php
LINE: 18
CALL: require('[ROOT]/stk/common.php')
Klicke hier um das STK neu zu laden.

I first had to turn it off. How to fix this or is it an error of the extension itself ?

**Comment by AlexSheer** [comment]
Of cource is it an error of the extension itself

**Comment by Galixte** [comment]
@miri4ever this extension: https://github.com/marcovo/phpbb_hidebbcode. Moreover, you should to know that this extension was stopped by his author: https://github.com/marcovo/phpbb_hidebbcode/issues/25#issuecomment-262037037. Don’t use with phpBB 3.2.x.
